version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=somepass
      - MYSQL_DATABASE=springbootapi
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  spring-boot-api-rest:
    image: spring-boot-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db/springbootapi
      - SPRING_DATASOURCE_USERNAME=user123
      - SPRING_DATASOURCE_PASSWORD=somepass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=somepass
      - MYSQL_ROOT_PASSWORD=root123
    links:
      - db